#!/bin/bash

# Oracle uninstall script
# This script deletes some oracle files and folders.
# Author: Yuriy Lazutin
# Site: lazutin.info
# Location: Tomsk, Siberia
# Creation: 2020-oct-11
# Donates:
#          https://www.paypal.com/paypalme/yuriylazutin
#          https://www.patreon.com/yuriylazutin

source environment

function DeleteObject {
  if sudo [ -e "${1}" ]; then
    echo "Removing \"${1}\": "
    sudo rm -rf "${1}"
    if [ $? -eq 0 ]; then
      echo -e "\033[1;32mDone\033[0m"
    else
      echo -e "\033[1;31mFailed\033[0m"
    fi
  fi
}

DeleteObject "/opt/ORCLfmap"
DeleteObject "${FILEMAPLOC}"
DeleteObject "${ORCLFMAPLOC}"
DeleteObject "/var/tmp/.oracle"
DeleteObject "/tmp/.oracle"
DeleteObject "${ORATAB}"
DeleteObject "/etc/oraInst.loc"
DeleteObject "${LBIN}/dbhome"
DeleteObject "${LBIN}/oraenv"
DeleteObject "${LBIN}/coraenv"
