#!/bin/bash

# Oracle uninstall script
# This script remove limits for oracle user
# Author: Yuriy Lazutin
# Site: lazutin.info
# Location: Tomsk, Siberia
# Creation: 2020-oct-16
# Donates:
#          https://www.paypal.com/paypalme/yuriylazutin
#          https://www.patreon.com/yuriylazutin

if [ -f /etc/security/limits.d/oracle.conf ]
then
  echo -n "Removing /etc/security/limits.d/oracle.conf: "
  sudo rm /etc/security/limits.d/oracle.conf
  if [ $? -eq 0 ]; then
    echo -e "\033[1;32mDone\033[0m"
  else
    echo -e "\033[1;31mFailed\033[0m"
  fi
fi
